import Bold from "components/style/bold";
import Line from "components/svgs/line";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { AcademicCapIcon } from "@heroicons/react/24/solid";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { SignInButton, UserButton } from "@clerk/nextjs";
import { SignIn, useUser } from "@clerk/clerk-react";

export default function Home() {
  const router = useRouter();
  const { user, isLoaded } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-[130vh] ">
        <div className="mx-[2rem] flex min-h-screen flex-col gap-[3rem]  pt-[2rem] ">
          <img src="/logo.png" className="mr-auto w-[40vw]" />
          <div className="flex flex-col  gap-[1.5rem]">
            <img src="kone.jpg" className="w-[90vw] rounded-xl shadow-md" />
            <div className="flex   flex-col gap-[0.5rem]">
              <div className="flex flex-row items-center gap-[0.5rem]">
                <AcademicCapIcon className="h-8 w-8 font-semibold text-green-600" />
                <div className="font-semibold text-green-600">
                  SELF-IMAGE BASED
                </div>
              </div>
              <div className="flex flex-col gap-0">
                {" "}
                <p className="text-white leading-12 text-3xl font-bold">
                  Climate Analysis with Novel AI
                </p>
                <Line />
              </div>
              <p className="text-gray-500">
                <span className="font-semibold text-white">
                  Rapid environmental
                </span>{" "}
                information for low-income nations worldwide..
              </p>
            </div>
            <div className="flex flex-row" onClick={() => router.push("")}>
              {isLoaded && user && (
                <button onClick={() => router.push("/uploadphoto")} className="rounded-lg bg-white px-4 py-3 text-left font-semibold text-green-600 shadow-lg">
                  Continue
                </button>
              )}
              {!isLoaded ||
                (!user && (
                  <SignInButton afterSignInUrl="/" afterSignUpUrl="/">
                    <button className="justify-left w-[15vw] rounded-md bg-white px-3 py-2 text-left font-semibold text-green-600 shadow-lg">
                      Sign In
                    </button>
                  </SignInButton>
                ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
