import Bold from "components/style/bold";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { AcademicCapIcon } from "@heroicons/react/24/solid"
import { api } from "~/utils/api";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#F7F7F7] h-[120vh]">
        <div className="mx-[2rem] mt-[1rem] flex min-h-screen flex-col ">
          <div>
            <img src="/logo.png" className="w-[40vw]" />
          </div>
          <div>
            <img src="/home_img.png" className="w-[90vw]" />
          </div>
          <div className="flex mb-[0.75rem] flex-row text-green-600">
            <AcademicCapIcon className="pl-[0.25rem] font-semibold text-green-600 h-8 w-8" />
            SELF-IMAGE BASED
          </div>
          <div className="mb-[1rem]">
            <p className="text-4xl font-extrabold leading-12">Climate Analysis with Novel AI</p>
            <p className="text-xl font-semibold leading-8">Rapid environmental <Bold text="information" /> for <Bold text="low-income nations" /> worldwide.</p>
          </div>
          <div className="pt-[1rem]">
            <button className="mr-[0.5rem] font-semibold shadow-md bg-white text-green-700 px-4 py-3 rounded-md">Sign Up</button>
            <button className="ml-[0.5rem] font-semibold text-gray-500">Login</button>
          </div>
        </div>
      </main>
    </>
  );
}

