import Bold from "components/style/bold";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { AcademicCapIcon } from "@heroicons/react/24/solid";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { SignInButton } from "@clerk/nextjs";
import { SignIn } from "@clerk/clerk-react";
import Card from "components/svgs/card";

export default function SteveYang() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100vh] bg-[#F7F7F7]">
        <div className="mx-[2rem] flex min-h-screen flex-col gap-[3rem] bg-[#F7F7F7] pt-[2rem] ">
          <img src="/logo.png" className="mr-auto w-[40vw]" />

          <div className="flex flex-col items-center justify-center gap-[0rem]">
            <div className="flex flex-row font-bold text-green-600">
              View Others
            </div>
            <div className="leading-12 content-center text-4xl font-bold">
              In your area.
            </div>
          </div>
          <Card
            img="kone.jpg"
            prof="/profile_one.png"
            loc="San Jose, CA"
            num="99"
          />
          <Card
            img="kone.jpg"
            prof="/profile_one.png"
            loc="San Jose, CA"
            num="99"
          />
          <Card
            img="kone.jpg"
            prof="/profile_one.png"
            loc="San Jose, CA"
            num="99"
          />

          {/* </div>
          <div>
            <img src="/home_img.png" className="w-[90vw]" />
          </div>
          <div className="mb-[0.75rem] flex flex-row text-green-600">
            <AcademicCapIcon className="h-8 w-8 pl-[0.25rem] font-semibold text-green-700" />
            SELF-IMAGE BASED
          </div>
          <div className="mb-[1rem]">
            <p className="leading-12 text-4xl font-extrabold">
              Climate Analysis with Novel AI
            </p>
            <p className="text-xl font-semibold leading-8">
              Rapid environmental <Bold text="information" /> for{" "}
              <Bold text="low-income nations" /> worldwide.
            </p>
          </div> */}
        </div>
      </main>
    </>
  );
}
